api_security:
  allowed_origins:
  - http://localhost:8501
  cors_enabled: true
  rate_limiting: true
  requests_per_minute: 60
authentication:
  enabled: true
  lockout_duration_minutes: 30
  max_login_attempts: 5
  method: jwt
  token_expiry_hours: 24
password_policy:
  min_length: 8
  require_lowercase: true
  require_numbers: true
  require_special_chars: false
  require_uppercase: true
session:
  httponly_cookies: true
  secure_cookies: true
  timeout_hours: 8
ssl:
  cert_file: ssl/cert.pem
  enabled: false
  key_file: ssl/key.pem
