# Configuration Template
# Copy this to your project and customize

# Project Settings
project_name: "my_ml_project"
experiment_prefix: "exp"

# Model Parameters
model:
  type: "RandomForest"
  n_estimators: 100
  max_depth: 10

# Data Settings
data:
  train_path: "data/train.csv"
  test_path: "data/test.csv"
  target_column: "target"

# Training Settings
training:
  test_size: 0.2
  random_state: 42
  cross_validation: 5
